name: 'MyApp Backup Action'
description: 'Initiates a multi-job repository backup process.'
branding:
  icon: 'archive'
  color: 'blue'

inputs:
  activation_code:
    description: 'Activation code for API'
    required: true
  encryption_password:
    description: 'Secret key for a more secure backup (min. 32 chars)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke the multi-job backup engine
      uses: berkayy-atas/marketplace-test-workflow/.github/workflows/backup-engine.yml@main
      with:
        encryption_password: ${{ inputs.encryption_password }}
        activation_code: ${{ inputs.activation_code }}
    
