name: 'MyApp Backup Action'
description: 'Repository mirror backup, ZSTD compression, and API upload. Optionally uses org ID.'
branding:
  icon: 'archive'
  color: 'blue'

inputs:
  activation_code:
    description: 'Activation code for API (passed as a secret)'
    required: true
  encryption_password:
    description: 'Secret key for encrypting the backup (min. 32 chars)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Invoke the multi-job backup engine
      uses: ${{ github.action_repository }}/.github/workflows/backup-engine.yml@${{ github.action_ref }}
      with:
        encryption_password: ${{ inputs.encryption_password }}
      secrets:
        ACTIVATION_CODE: ${{ inputs.activation_code }}
