name: 'MyApp Backup Action'
description: 'Repository mirror backup, ZSTD compression, and API upload. Optionally uses org ID.'
branding:
  icon: 'archive'
  color: 'blue'

inputs:
  activation_code:
    description: 'Activation code for API'
    required: true
  encryption_password:
    description: 'Secret key for encrypting the backup (min. 32 chars)'
    required: true
 
    
runs:
  using: 'composite'
  steps:
    - name: Validate encryption password length
      shell: bash
      run: ${{ github.action_path }}/scripts/validate_password.sh
      env:
        INPUT_ENCRYPTION_PASSWORD: ${{ inputs.encryption_password }}

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Clone Repository in Mirror Mode
      shell: bash
      run: ${{ github.action_path }}/scripts/clone_mirror.sh

    - name: Install Dependencies
      shell: bash
      run: ${{ github.action_path }}/scripts/install_deps.sh

    - name: Encrypt Compressed Repository
      shell: bash
      run: ${{ github.action_path }}/scripts/create_archive.sh
      env:
        INPUT_ENCRYPTION_PASSWORD: ${{ inputs.encryption_password }}

    - name: Get Activation Token
      shell: bash
      run: ${{ github.action_path }}/scripts/get_token.sh
      env:
        INPUT_ACTIVATION_CODE: ${{ inputs.activation_code }}

    - name: Upload Backup to Shield API
      shell: bash
      run: ${{ github.action_path }}/scripts/upload_backup.sh

    - name: Print Backup Summary
      shell: bash
      run: ${{ github.action_path }}/scripts/print_summary.sh
