#.github/workflows/reusable-backup-workflow.yml

name: Reusable Backup Workflow with Cache

on:
  workflow_call:
    inputs:
      backup-file-name:
        description: 'Name for the backup archive file.'
        required: true
        type: string
      source-path:
        description: 'Path to the directory or file to back up.'
        required: true
        type: string
    secrets:
      activation_code:
        description: 'Activation code for the backup service'
        required: true
      encryption_password:
        description: 'Password to encrypt the backup archive'
        required: true

# Her iş akışı çalıştırması için benzersiz bir önbellek anahtarı tanımlıyoruz.
env:
  BACKUP_CACHE_KEY: backup-cache-${{ github.run_id }}-${{ inputs.backup-file-name }}

jobs:
  # 1. İş: Arşivle, Şifrele ve Önbelleğe Kaydet
  create_encrypt_and_cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create backup archive
        run: |
          zip -r ${{ inputs.backup-file-name }} ${{ inputs.source-path }}
      
      - name: Encrypt the archive
        run: |
          echo "Encrypting ${{ inputs.backup-file-name }}..."
          # Gerçek şifreleme komutu (örneğin openssl) burada kullanılmalıdır.
          # openssl enc -aes-256-cbc -salt -in ${{ inputs.backup-file-name }} -out ${{ inputs.backup-file-name }}.enc -k "${{ secrets.encryption_password }}"
          mv ${{ inputs.backup-file-name }} ${{ inputs.backup-file-name }}.enc
          echo "Encryption complete."

      # Artifact yerine, şifrelenmiş dosyayı önbelleğe kaydediyoruz.
      - name: Save encrypted backup to cache
        uses: actions/cache/save@v4
        with:
          path: ${{ inputs.backup-file-name }}.enc
          key: ${{ env.BACKUP_CACHE_KEY }}

  # 2. İş: Önbellekten Geri Yükle ve Depolamaya Yükle
  upload:
    runs-on: ubuntu-latest
    needs: create_encrypt_and_cache
    steps:
      # Artifact yerine, şifrelenmiş dosyayı önbellekten geri yüklüyoruz.
      - name: Restore encrypted backup from cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ inputs.backup-file-name }}.enc
          key: ${{ env.BACKUP_CACHE_KEY }}
          # Bu parametre kritik öneme sahiptir: Önbellek bulunamazsa, iş başarısız olur.
          fail-on-cache-miss: true
      
      - name: Authenticate with Activation Code
        run: |
          echo "Authenticating with the provided activation code..."
          # export MY_SERVICE_TOKEN="${{ secrets.activation_code }}"
          echo "Authentication successful."

      - name: Upload to final destination
        run: |
          echo "Uploading ${{ inputs.backup-file-name }}.enc to the backup storage..."
          ls -lh ${{ inputs.backup-file-name }}.enc
          echo "Upload complete."

  # 3. İş: Geçici Önbelleği Temizle
  cleanup:
    runs-on: ubuntu-latest
    # Bu iş, önceki işlerin sonucuna bakılmaksızın her zaman çalışır.
    if: always()
    needs: [upload]
    # Önbelleği silebilmek için 'actions: write' izni gereklidir.
    permissions:
      actions: write
    steps:
      - name: Clean up temporary backup cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Cleaning up cache with key: ${{ env.BACKUP_CACHE_KEY }}"
          gh cache delete "${{ env.BACKUP_CACHE_KEY }}" --confirm |

| echo "Cache entry not found or already deleted."
